const INGREDIENT_LABELS_FR: Record<string, string> = {
  almond: "Amande",
  apple: "Pomme",
  avocado: "Avocat",
  banana: "Banane",
  beef: "Boeuf",
  "bell pepper": "Poivron",
  broccoli: "Brocoli",
  "brown rice": "Riz complet",
  carrot: "Carotte",
  chicken: "Poulet",
  chickpea: "Pois chiche",
  cinnamon: "Cannelle",
  cucumber: "Concombre",
  egg: "Oeuf",
  garlic: "Ail",
  ginger: "Gingembre",
  "greek yogurt": "Yaourt grec",
  "green bean": "Haricot vert",
  lentil: "Lentille",
  lettuce: "Laitue",
  milk: "Lait",
  mushroom: "Champignon",
  oat: "Avoine",
  "olive oil": "Huile d'olive",
  onion: "Oignon",
  peanut: "Arachide",
  pork: "Porc",
  potato: "Pomme de terre",
  quinoa: "Quinoa",
  rice: "Riz",
  salmon: "Saumon",
  shrimp: "Crevette",
  spinach: "Epinard",
  sugar: "Sucre",
  "sweet potato": "Patate douce",
  tofu: "Tofu",
  tomato: "Tomate",
  tuna: "Thon",
  turkey: "Dinde",
  walnut: "Noix",
  wheat: "Ble",
  "whole wheat": "Ble complet",
  yogurt: "Yaourt",
};

export function getIngredientLabel(value: string): string {
  const normalized = value.trim().toLowerCase();
  return INGREDIENT_LABELS_FR[normalized] || value;
}

