import { MealRecommendation } from "@/lib/types";

export const mockMeals: MealRecommendation[] = [
  {
    id: "1",
    title: "Grilled Chicken Quinoa Bowl",
    calories: 620,
    protein: 42,
    carbs: 48,
    fat: 18,
    tags: ["High protein", "Balanced", "Lunch"],
    description: "A balanced bowl with grilled chicken, quinoa, avocado and roasted vegetables.",
    ingredients: ["Chicken", "Quinoa", "Avocado", "Broccoli", "Carrots"],
    matchReason: "Fits an active lifestyle with a strong protein intake.",
  },
  {
    id: "2",
    title: "Salmon Sweet Potato Plate",
    calories: 680,
    protein: 39,
    carbs: 44,
    fat: 26,
    tags: ["Omega-3", "Dinner", "Gluten free"],
    description: "Oven-baked salmon with sweet potato and green beans.",
    ingredients: ["Salmon", "Sweet potato", "Green beans", "Olive oil"],
    matchReason: "Supports heart health and recovery with nutrient-dense ingredients.",
  },
  {
    id: "3",
    title: "Greek Yogurt Berry Breakfast",
    calories: 360,
    protein: 24,
    carbs: 30,
    fat: 10,
    tags: ["Breakfast", "Quick", "High protein"],
    description: "Greek yogurt with berries, oats and chia seeds.",
    ingredients: ["Greek yogurt", "Blueberries", "Oats", "Chia seeds"],
    matchReason: "A light, protein-rich breakfast aligned with weight management.",
  },
];